### ISSUE TITLE
gulp-w3cjs does not work anymore

### ISSUE THREAD

**Issue by coderPaddyS** [studierlangsam/webseite#48]
gulp-w3cjs uses deprecated dependencies and fails. Therefore the pipeline fails

**Comment by jGleitz** [comment]
Thanks for leaving this issue as a reminder. The right thing to do would be to pull the repo onto a modern build system like webpack. But I currently have no time for that. In the meantime, we should probably find another HTML validator. w3cjs had found multiple valid issues in the past.

**Comment by jGleitz** [comment]
Fixed with move to Svelte
