### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by jGleitz** [studierlangsam/webseite#7]
We should have CI which
 1. builds the site on every PR, to check that the build still works.
 2. Deploys every push to `main` automatically.

Bonus points for deploying every branch somewhere where we can see a preview.

**Comment by jGleitz** [comment]
To make the automation easier, we can stop using version numbers for docker images, and simply tag them with the git commit id the were built from.

**Comment by coderPaddyS** [comment]
I've just discovered a CI to build and deploy to Github Pages automatically, more [here](https://github.com/marketplace/actions/deploy-to-github-pages). Could a small adaptation of this work for us?
